### ISSUE TITLE
Doesn't launch with Wine

### ISSUE THREAD

**Issue by 4bitFox** [Assistant/ModAssistant#129]
I can't get ModAssistant to work with Wine (Staging 5.5).

Running ModAssistant in new Wine prefix:
`The entry point method could not be loaded due to Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.`

After installing dotNet45:
`wine: Call from 0x7bc92a49 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting`

Logfile:
[playonlinux.log](https://github.com/Assistant/ModAssistant/files/4568369/playonlinux.log)

Am I missing a dependency?

Edit: Last line in the log file is from me terminating ModAssistant because it turned into a zombie process.

**Comment by Jverm84** [comment]
Your missing me. Do you want me to solve this riddle and find my handler?

**Comment by Assistant** [comment]
I can't remember exactly what I had configuration-wise on wine, but I believe dotnet45 is probably too old, might need dotnet46 or similar, consider the project is targeted to 4.6.2

**Comment by 4bitFox** [comment]
I tried it with dotNet461 and it launches, except it can't download the Versions list. If i remember correctly there was a similar problem with the classic Mod Manager.

This time there is nothing interesting in the log:
`[05/07/20 12:27:22] - Running wine- ModAssistant.exe (Working directory : /home/fabian/.PlayOnLinux/wineprefix/BeatSaber_ModAssistant/drive_c)`

![Screenshot_20200507_121309](https://user-images.githubusercontent.com/33175205/81283728-60e1f200-905d-11ea-965d-193a5cd7673c.png)

**Comment by Jverm84** [comment]
Is Linux just harder to hack?

**Comment by megalon** [comment]
How does wine handle networking?
I think getting the game versions from Beat Mods is the first network request that MA makes, so if wine is blocking network requests behind a firewall or something, then it could fail.

**Comment by WebFreak001** [comment]
mods installing fine here, are you using the correct wine prefix?

For me I ran
```
env WINEPREFIX=$HOME/.steam/steam/steamapps/compatdata/620980/pfx winetricks
```
to install net461

then I ran
```
ln -s ~/.steam/steam/steamapps/common/Beat\ Saber/ ~/.steam/steam/steamapps/compatdata/620980/pfxdrive_c/Program\ Files/
```
because ModAssistant didn't like my Beat Saber folder not being on the C: drive (but on the Z: drive)

then I selected it in ModAssistant and installed mods as usual.



If some error like "This application could not be started" pops up when trying to run Beat Saber, close it again and make sure wineserver is killed:
```
env WINEPREFIX=$HOME/.steam/steam/steamapps/compatdata/620980/pfx wineserver -k
```

also make sue all winedevice.exe and other running .exe processes are killed. Make sure there is no trace left of wine.



However even though no error messages pop up anymore, I don't think any mods are loaded? I never installed mods for Beat Saber before so I don't know what to look out for but for the installed Core Mods I don't see any changes in the menus. The "Beat Saber/Plugins" folder is also empty but it seems there is some new IPA folder which I don't know what it's for.

**Comment by WebFreak001** [comment]
ok I copied all the files from IPA/Pending into the Beat Saber directory itself and added a winhttp override to the proton registry as described here: https://bsmg.wiki/modding/linux.html#dll-override

now mods seem to work

**Comment by 4bitFox** [comment]
I just had a brainwave!

I found out that I can share a folder with a VM, so i just did that and guided ModAssistant to it (with a symlink).
![Screenshot_20200517_154622](https://user-images.githubusercontent.com/33175205/82148944-a79dcc00-9855-11ea-8ed9-329651cefa8c.png)
![Screenshot_20200517_154234](https://user-images.githubusercontent.com/33175205/82148626-0adb2e80-9855-11ea-8e46-960b9a719167.png)

With this and WebFreak001s help i got the Mods running.
> ok I copied all the files from IPA/Pending into the Beat Saber directory itself and added a winhttp override to the proton registry as described here: https://bsmg.wiki/modding/linux.html#dll-override

This could be a potential fix for the networking problem if anyone needs it, but I havn't tried.
https://wiki.winehq.org/FAQ#My_program_fails_to_do_networking.2C_but_my_other_applications_can_get_online

Thank you guys!
