### ISSUE TITLE
Settings page feels super cluttered

### ISSUE THREAD

**Issue by Parapass** [Assistant/ModAssistant#181]
This is what the settings page currently looks like:
![image](https://user-images.githubusercontent.com/59424861/83519706-7b678980-a4aa-11ea-86da-69f50b70d3d4.png)
This is what it will look like if we make the OneClick a ComboBox.
![image](https://user-images.githubusercontent.com/59424861/83520520-d188fc80-a4ab-11ea-8637-234a4e090e45.png)
I'll PR this with extra polishing.

**Comment by megalon** [comment]
Yes, the options page is getting really crowded.
Have you tried using WPF's Menu and MenuItem elements instead of a ComboBox?
https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/menu-overview

Although MA currently doesn't use it, but I added the styles for it a while ago, so it should be theme compatible. Might save you some trouble with styling
