### ISSUE TITLE
Blank menu (Game is unplayable)

### ISSUE THREAD

**Issue by Coolhusky333** [Assistant/ModAssistant#22]
I just got the game played a level and then decided to download mod manager. Now I cant even play it.

**Comment by Assistant** [comment]
This program only installs mods, refer to the [BSMG Wiki](https://bsmg.wiki/support#3-1-blank-menu-no-buttons) to find solutions to problems caused by mods or just general problems with the game.

However, if you can zip up and upload the folder the wiki tells you to delete I can see about having Mod Assistant detect and fix it.
