### ISSUE TITLE
No song Loader

### ISSUE THREAD

**Issue by mrfanservice** [Assistant/ModAssistant#23]
Hi, sorry if this is a stupid question, i m a novice with all of that. is it normal that a dont have the song loader Mod in the mod menu?
thanks

**Comment by PG8205** [comment]
im having the same exact problem wtf

**Comment by Jace669** [comment]
Any word on getting custom song library back into the latest version?

**Comment by megalon** [comment]
SongCore now converts your existing song library to the game's default format.
It preserves the old `.json` files, but generates new `.dat` files. In the process it moves everything into the `Beat Saber\Beat Saber_Data\CustomLevels\` folder, so that the game can load them even without mods.

Once they are converted, they will appear in the game's default CustomMaps level pack.
See this image below
![image](https://user-images.githubusercontent.com/27714637/59241952-88ff7180-8bbe-11e9-8489-1ed826a644c1.png)

Visit the #support channel on the Beat Saber Modding Group Discord for more help.
https://discord.gg/beatsabermods
