### ISSUE TITLE
wrong game type?

### ISSUE THREAD

**Issue by sqooper** [Assistant/ModAssistant#274]
i play beat saber on steam with my vive, but modassistant says my game type is oculus and i can't figure out how to change it

**Comment by shedowhammer** [comment]
I have the same problem, I don't have Oculus installed and it still says game type Oculus. I have the game on steam.

**Comment by okawo80085** [comment]
wouldn't you know it, same here

im not using an oculus headset, but my game type is set to oculus

**Comment by Charizmare** [comment]
My mod assistant is doing the same thing. The only I have to fix it is to uninstall and then reinstall the mod assistant. Even then though, it goes back to saying oculus

**Comment by ChucklesTheBeard** [comment]
Workaround until that fix gets merged:

1. Open Notepad.
2. Save an empty file at `$BEAT_SABER_DIR\Beat Saber_Data\Plugins\`
3. Name it `steam_api64.dll`

(if the file icon you created looks like a notepad instead of a DLL, turn file extensions on - open any folder in explorer -> "view" tab at the top -> "Options" -> "view" tab -> scroll down and uncheck "Hide file extensions for known file types" and try again)
