### ISSUE TITLE
IDP Virus?

### ISSUE THREAD

**Issue by BigBoss0-1** [Assistant/ModAssistant#282]
My antivirus says the .exe file contains a IPD Virus

**Comment by lolPants** [comment]
Unfortunately some AV engines will detect ModAssistant as a virus, likely due to it reading the registry to determine your installation path and downloading mod DLLs from an external server. There's nothing we can do to stop AV engines flagging the `.exe`, you will have to trust that this software is legitimate.

All source code is publicly documented on this repo, and all releases are automatically built from source by GitHub actions. If you don't trust those builds you can always build ModAssistant yourself.

Additionally, all mods that ModAssistant downloads are pulled from [BeatMods](https://beatmods.com/), which are all scanned and approved for download manually by a team of volunteers.
