### ISSUE TITLE
Couldnt find a file

### ISSUE THREAD

**Issue by SmugTheKiler** [Assistant/ModAssistant#336]
Tells me "Could not detect your Beat Saber Installer folder. Please select it manually. " I have it on my oculus, but not on pc.

**Comment by SmugTheKiler** [comment]
BMBF does everything but when I try to lunch it through it it just puts up a black screen @Melopod

**Comment by Melopod** [comment]
Sounds like a common error caused by using the current version of BMBF which is incompatible with the current version of the game.
Again, Mod Assistant is for PC VR only. It won't help you mod a Quest copy of the game. If you continue having issues with your Quest, consider asking in the Quest support channel in the Beat Saber Modding Group on Discord, or downgrading via the Beat Saber Legacy Group, also on Discord
