### ISSUE TITLE
Why not .NET 5?

### ISSUE THREAD

**Issue by kcrg** [Assistant/ModAssistant#357]
Hi,

Is there any reason why this project is built on top of old .NET Framework instead of .NET 5?
In theory this should help run this app in Linux through Proton/Wine (#285)

If you like, I can contribute and send pull request with migrate project to .NET 5 and with some improvements like enabled [nullable](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/upgrade-to-nullable-references).

**Comment by Assistant** [comment]
A few reasons:

**Single file, compatibility, and filesize:** I want Mod Assistant to compile to a single file, which the latest version is 660KB, due to being able to leverage dynamic libraries already found in Beat Saber playing computers. Sure, a single file could be accomplished with .NET 5, but even with tree shaking and other techniques to reduce filesize, last time I tested it a Hello World compiled into a ~30MB file, and with a Hello World with UI that went up to ~100MB. Regarding Linux compatibility, Mod Assistant already works perfectly through Wine in my tests (although it doesn't perform workarounds needed for modding in Linux like a proper Linux mod installer would, but that's not the framework's fault).

**Time & effort:**  Even without the above issues, I don't think doing a framework upgrade, an then dealing with the long term maintenance and fixing any bugs that might arise, is the best use of anyone's time currently. Mod Assistant was designed to be used with [BeatMods](https://github.com/bsmg/BeatMods-Website#readme), which is sorely due for replacement soon. I'd keep my eye out for future projects being written from the ground up in .NET 5 and other modern technologies.

**Comment by Clintonio** [comment]
Saving space really shouldn't matter, it's not an optimisation that has any real impact with modern internet and storage solutions.

Not wanting to spend the time upgrading on the other hand makes sense. But if someone made the effort to do a PR and it was rejected I'd honestly confused if it were just to save a few megabytes on downloads.

**Comment by Assistant** [comment]
It's nice that your modern internet allows you to not care if a 600KB file becomes 150MB, but that's not the case for everyone, myself included. 

The issue poster actually already did the work required for a PR, but that doesn't address the ongoing maintenance that can be expected to arise from a framework upgrade. I'm guessing they knew that and that's why they opened the issue to ask for interest instead of just PRing their fork when they were done.

**Comment by ShayBox** [comment]
> It's nice that your modern internet allows you to not care if a 600KB file becomes 150MB, but that's not the case for everyone, myself included.

The program downloads libraries and mods that are many times larger than the program itself, for a base game and custom songs that are many magnitudes larger.

My game is almost 50gb total, nobody that's using mod assistant and custom mods are worried about binary size, including you.

**Comment by Assistant** [comment]
Weird flex but ok
