### ISSUE TITLE
crashing issue and repeated text

### ISSUE THREAD

**Issue by Loukylor** [Assistant/ModAssistant#42]
For some reason the text repeats seen here in the attached file
![Screenshot (11)](https://user-images.githubusercontent.com/46853114/64095143-d5b49d80-cd12-11e9-8bd6-d678afd22c1f.png)
 Note i used to get the issue where a giant error box in another issue pops up when i launched, or if i was lucky, got past launch and clicked a box next to a mod to select. but for some reason it doesn't occur anymore

**Comment by Loukylor** [comment]
its completely fixed by switching off check installed mods in the settings

**Comment by legoandmars** [comment]
Since this issue isn't solved yet, I thought I would highlight a more specific way to replicate this.

`Check Installed Mods` needs to be enabled in the settings.

When the launcher starts, click the `Mods` tab, the `Intro` tab, click `I Agree`, and then click the `Mods` tab again in quick succession. 

The program will glitch out and load all mods twice, which causes the UI error outlined in the main issue.

GIF Example: 
https://gfycat.com/totalgrizzledbluebottle

**Comment by megalon** [comment]
Closing because this issue seems to be fixed.
