### ISSUE TITLE
Cannot select version

### ISSUE THREAD

**Issue by KnownOriginator** [Assistant/ModAssistant#453]
Every other button in the UI works just fine, but I cannot select a different version of the game to install. I have 1.19 but I want 1.18.3 as well for the chatcore and twitch chat mods.

**Comment by Assistant** [comment]
That is intentional, Mod Assistant detects your game version and allows you to install the mods that have been verified to work with that version. Installing mods for a different version is unlikely to work, and will potentially break your install. If you're certain those mods will work you'll have to install them manually.

**Comment by Allibateus** [comment]
I get that, but when it was working, I used this to check if the mods are done for the newer version to know if I can upgrade or not. Now its impossible. 
Is it possible to like add a experimental checkbox in settings to change the verison to check?

**Comment by Assistant** [comment]
You can check [BeatMods](https://beatmods.com/#/mods) directly.
