### ISSUE TITLE
Unhandled exception with OneClick on BeatSaver

### ISSUE THREAD

**Issue by xhuytox** [Assistant/ModAssistant#5]
![image](https://user-images.githubusercontent.com/20061642/58137012-38ab7a00-7be5-11e9-9c22-3a4a3c9fc61d.png)

**Comment by theholyone** [comment]
Found the Reason in Classes/OneClickInstaller.cs , Line: 48 
`string ID = uri.Segments.Last<string>();`
Returns "/" instead of e.g.: "1234-1234"

Reason for this is that uri.Segments 'drops' the hostname:port and returns only the segments after it. For example, http://www.github.com/Assistant will only return "/" and "Assistant" as segments but never github.com itself. But on Beat Saver the OneClick install Button will start ModAssistant with "--install" "beatsaver://1183-814" which has no segment at all or at least an ending "/" in case it will be transformed to a well formated uri which seems to be the case.

**Comment by Assistant** [comment]
I was just about to take a look at it. This was an oversight from when the uri was `://songs/967-650` instead of `://967-650` that is now.

Thanks for finding it!
