### ISSUE TITLE
Add Chinese support

### ISSUE THREAD

**Issue by wgzeyu** [Assistant/ModAssistant#64]
Due to language barriers, some Chinese players have not learned to use ModAssistant, and even now (most Mods have been updated) they still think that Beat Games is killing Mods. In Beat Saber's Chinese negative reviews, most of them are scolding Beat Games to kill Mods.
I really ca n’t stand it, so I hope you can add Chinese support to this software. Although I can't write C #, I can speak Chinese. I translate most of the text in the software into Chinese:
https://github.com/wgzeyu/ModAssistant
Hope you can add a language option and set this option to Chinese by default when the system language is Simplified Chinese / Traditional Chinese.
![Chinese](https://wgzeyu.gtxcn.com/img/ma.png)

**Comment by Assistant** [comment]
Adding different languages is a lot harder than it seems it would be, and it would bulk up the executable and go against one of the main design philosophies of the project.
A solutions could be that someone can maintain a localized fork of the project and change its update route to that fork, since unless there's some breaking changes to the APIs, updates aren't needed when new game versions or mods are released, it could work well. Another would be to create an in depth guide to Mod Assistant including that information that the Chinese audience doesn't understand currently, and have it be prominent in the Chinese community. This is what the Japanese players have done.

**Comment by wgzeyu** [comment]
Okay, so let me maintain this Chinese branch.
Some people have made a guide to using ModAssistant and Mods, but some people do not plan to watch these videos.

**Comment by Assistant** [comment]
Make sure to change the update URL, otherwise whenever I update the main program everyone using your fork will be forced into the update.

https://github.com/Assistant/ModAssistant/blob/eab45842d8e84d08d87225811168e0a935c0a4d7/ModAssistant/Classes/Updater.cs#L17
