### ISSUE TITLE
No songs displaying since BS is in v1.7.0

### ISSUE THREAD

**Issue by lmillet06** [Assistant/ModAssistant#85]
There is no songs displaying in the menu since beatsaber is in version 1.7.0.

**Comment by sidju** [comment]
If I may propose a solution:
1: Open Mod Assistant
2: Open the "Intro" page in Mod Assistant
3: Read the Introduction. Especially the part that reads "Mods will break every update. This is normal..."
4: Uninstall all mods and restore your game files (Should be possible without reinstalling), to have the basic functional game with the songs you have previously imported before while you...
5: Take it easy and wait for the new versions of Mods to be released, which will most likely work just as you'd expect.

In essence, due to no mods existing for the 1.7 version of beatsaber no mods will work.
Installing mods for other versions is likely to break your game, perhaps causing songs to not show up.
The best course of action is to disable any mods for the wrong version, restore game files if problems persist and enjoy the base game while letting the amazing mod developers do their thing in peace.
